### ISSUE TITLE
io_path resource should stop io services in single node cluster also

### ISSUE THREAD

**Issue by ajay-paratmandali** [Seagate/cortx-ha#190]
Currently io path is only stopping cluster ip but in single node if there is hw fault stack not getting stop.

**Comment by ajay-paratmandali** [comment]
This can be difficult to stop io stack on single node as

- It can stop consul and cause control stack stop.
- GUI also will not be available.

**Comment by mssawant** [comment]
@ajay-paratmandali , can please elaborate on this? the use case if not very clear from the description.

**Comment by ajay-paratmandali** [comment]
This issue created for
Problem:
In R1 if one node down and io-stack running on one node then if iostack down on this node will cause failure to consul and due to this management and sspl service also get failed.

It is expected behavior in R1 it will get resolved for R2
Closing this issue.
