### ISSUE TITLE
Add all log for corosync in support bundle

### ISSUE THREAD

**Issue by ajay-paratmandali** [Seagate/cortx-ha#252]

**Comment by indrajitzagade** [comment]
> 
> 
> This issue/pull request has been marked as `needs attention` as it has been left pending without new activity for 4 days. Tagging @indrajitzagade @ajaysrivas for appropriate assignment. Sorry for the delay & Thank you for contributing to CORTX. We will get back to you as soon as possible.

@ajay-paratmandali Please add reviewers to this PR.

**Comment by ajay-paratmandali** [comment]
We need to add all logs for support bundle. Currently it only collecting single file and not log rotated files.

https://github.com/Seagate/cortx-ha/pull/254
https://github.com/Seagate/cortx-ha/pull/253

254 already fixed in main branch.
253 patch is for cortx-1.0 branch in review state.

cc: @ajaysrivas  @indrajitzagade

**Comment by ajay-paratmandali** [comment]
This is fixed in main branch not needed and can be closed.
