### ISSUE TITLE
build-ha-io script doesn't log anything

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-ha#256]
`build-ha-io` and group of similar scripts don't use logging at all. Instead all the messages are echo'ed to stdout that causes problems while investigating of deployment issues.

Solution: log messages to syslog.

**Comment by indrajitzagade** [comment]
> 
> 
> This issue/pull request has been marked as `needs attention` as it has been left pending without new activity for 4 days. Tagging @indrajitzagade @ajaysrivas for appropriate assignment. Sorry for the delay & Thank you for contributing to CORTX. We will get back to you as soon as possible.

@knekrasov Please add reviewers to this PR.

**Comment by knekrasov** [comment]
@indrajitzagade it is an issue, not a PR.

**Comment by indrajitzagade** [comment]
> 
> 
> @indrajitzagade it is an issue, not a PR.

@knekrasov Yes :)

**Comment by azheregelya** [comment]
https://github.com/Seagate/cortx-ha/pull/260 PR addresses this issue.

**Comment by ArchanaLimaye** [comment]
@knekrasov , which branch is this change needed in  ?

**Comment by knekrasov** [comment]
@ArchanaLimaye In main, I guess.

**Comment by ArchanaLimaye** [comment]
> @ArchanaLimaye In main, I guess.

Thanks.  #260 is raised on main so it will handle this issue
