### ISSUE TITLE
No CIB access when cluster is stopped

### ISSUE THREAD

**Issue by azheregelya** [Seagate/cortx-ha#288]
@ajay-paratmandali @ajaysrivas @indrajitzagade 
During testing, i found one nasty thing - CIB can't be accessed whey cluster is in Stopped state.
This means that:
*  `pcs property set stonith-enabled=False` command will fail.
* `pcs cluster cib` command will also fail.
* `pcs cluster cib-push` command also shall be executed on running cluster. 

So, to setup properties and to get CIB file for `create_cluster_resources` we need to run cluster at least once for some time.
I checked whether `pcs setup` provides options to specify properties on setup - no, it doesn't

So, having in mind pull requests #283 #281, i would suggest to discuss how we can workaround/solve aforementioned problem.

Proposal 1:
Since at least one time cluster shall be started, I would suggest to slightly change `create_cluster()` function behavior in following manner:
* Setup with `--start` option first time without regard to 'start' parameter passed.
* Run cib_get() function to populate CIB file for further use by HA mini provisioner. This means that `cib_xml` parameter will be added and the same string will be returned back if CIB was generated successfully, `None` otherwise.
* Call `pcs cluster stop` to stop the cluster.

Since `cib-push` shall be done also on running cluster, `create_all_resources` function will only populate `cib_xml`.  Start and push operations will be done explicitly in this case - i'm just not sure where it is worth doing such things explicitly in HA mini provisioner or create some wrapper function for that.
In any way, looks like CIB file is the thing we shall take care off during provisioning process.

Proposal 2 which will work **only** for M0 milestone:
* Start cluster during setup. Minimal changes are required
* Create resources as planned. No changes here.
* Set stonith-enabled property to False in the very end and stop the cluster.
Such approach allows to create resources on alive cluster - they will be in stopped state until property is changed

Proposal 3: put current node into standby mode and do all operations on alive cluster.
Not much details here since i haven't tried that approach yet.

A question might appear - why we need that cib_xml at all? Answer is - we need it to apply changes in logical chunks - atomically from component point of view. The also allows to reduce unnecessary migrations within cluster during setup.

So, what do you think?

**Comment by ajay-paratmandali** [comment]
@azheregelya 

i think
```
Proposal 3: put current node into standby mode and do all operations on alive cluster.
Not much details here since i haven't tried that approach yet.
```
it look good

**Comment by azheregelya** [comment]
Implemented proposal 3.
