### ISSUE TITLE
Should SimpleProcess go to cortx-utils

### ISSUE THREAD

**Issue by ajaysrivas** [Seagate/cortx-ha#290]
SimpleProcess in HA code may me contributed to cortx-utils.
Please investigate and if it makes sense move it to cortx-utils.

**Comment by hessio** [comment]
Hi @ajaysrivas what is the status of this issue? Did you figure out if this code needed to be moved?

**Comment by hessio** [comment]
Hi @ajaysrivas can you provide an update on this issue, I have sent an email regarding the same?

**Comment by ajaysrivas** [comment]
@hessio This is already done. I am closing the issue.

**Comment by cortx-admin** [comment]
> Mukhtar Inamdar commented in Jira Server:

I checked this issue([https://github.com/Seagate/cortx-ha/issues/290)] it has been closed by [~743532]. He commented on it as it is already done, hence I am closing this shadow issue.

**Comment by cortx-admin** [comment]
> Mukhtar Inamdar commented in Jira Server:

I checked this issue([https://github.com/Seagate/cortx-ha/issues/290)] it has been closed by [~743532]. He commented on it as it is already done, hence I am closing this shadow issue.

**Comment by cortx-admin** [comment]
> Mukhtar Inamdar commented in Jira Server:

I checked this issue([https://github.com/Seagate/cortx-ha/issues/290)] it has been closed by [~743532]. He commented on it as it is already done, hence I am closing this shadow issue.

**Comment by cortx-admin** [comment]
> Mukhtar Inamdar commented in Jira Server:

I checked this issue([https://github.com/Seagate/cortx-ha/issues/290)] it has been closed by [~743532]. He commented on it as it is already done, hence I am closing this shadow issue.
