### ISSUE TITLE
Problem: argparse library makes pcswrap unreadable

### ISSUE THREAD

**Issue by b3ee2b06-d749-479e-a0eb-ef1bf6980532** [Seagate/cortx-ha#57]
CLI parsing logic is currently done with argparse library. pcswrap has
quite complex CLI structure which turns into long and not obvious
argparse-specific code and result processing is tricky as well. This
makes the code error-prone.

Solution: use click library instead of argparse.

Closes http://gitlab.mero.colo.seagate.com/mero/hare/issues/405

**Comment by azheregelya** [comment]
The issue is relevant for R1 only ATM and can be reopened if needed.
